CREATE DATABASE IF NOT EXISTS mooket_source CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS mooket_erp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS mooket_uac CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
